### ISSUE TITLE
Escrever frontpage do site oficial da comunidade

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#1]
Sugestões de tópicos:

- [x] Cursos abertos de Common Lisp + Tutoriais
- [x] Links de livros da Amazon ou outras livrarias (recomendados por quem já leu e que se pretende ler)
- [x] Tutorial pra configurar Quicklisp e SLIME (de preferência, com quicklisp)

Interessante pela acessibilidade seria os tópicos serem em português, mas como isso é um tanto improvável no começo, procuraremos o máximo de referências em português boas e o que não acharmos colocamos o link em inglês. Cada link era bom ter anotado ao lado com a tag da linguagem, tal como: `EN` ou `PT`.

Qualquer conteudo relacionado, o indívudo é bem-vindo a compartilhar nesse issue.

Outros links interessantes:

- [x] Lisperati Casting Spells Tour: http://www.lisperati.com/casting.html
- [x] Common Lisp REPL Exploration Guide: http://bnmcgn.github.io/lisp-guide/lisp-exploration.html
- [x] Trocar YASWEG por https://github.com/kingcons/coleslaw (?)
- [ ] Referência PT_BR Scheme vs Common Lisp: http://inf.ufrgs.br/~vbuaraujo/fundalg/olden/about-lisp.html
- [ ]  CL |> JS: https://common-lisp.net/project/parenscript/

**Comment by ryukinix** [comment]
Outros links interessantes:

- [ ] Lisperati Casting Spells Tour: http://www.lisperati.com/casting.html
- [ ] Common Lisp REPL Exploration Guide http://bnmcgn.github.io/lisp-guide/lisp-exploration.html

**Comment by ryukinix** [comment]
> Cool ! On reading:
> * "the lisps have a syntax based on parenthesis" in the introduction: I wouldn't myself emphasize on  > the parenthesis, but speak about higher language features (a bit like code/data, that comes after)
> * links: the Hyperspec and the (shitty) Cliki as the first two links is a bit arsh, IMO :S No love for http://lisp-lang.org/ ? For the Cookbook and https://github.com/CodyReichert/awesome-cl ? :(
> * Configuring Quicklisp: no love for https://lispcookbook.github.io/cl-cookbook/getting-started.html ? :D more complete than the QL doc IMO.
> * your link to installing Slime gives the instructions to install from source :S there are more solutions, as listed in the "getting started" above.
> * no love for Portacle ? Lem maybe ? https://lispcookbook.github.io/cl-cookbook/editor-support.html
> * I wouldn't say the nEXT browser is totally written in Lisp, it uses bindings to webkit on Linux.
> * for a list of project: what about https://github.com/azzamsa/awesome-cl-software ?
> * you link to YASWEG, in Guile. What about https://github.com/kingcons/coleslaw ?

> In general, I'd like to push towards the Lisp Cookbook… Would you be interested in translating and extending it ? If you write portuguese content that would fit in, tell us, we can link to it, and I can help with translation.

Comentário do reddit: https://www.reddit.com/r/lisp/comments/7wqgy5/common_lisp_brazil_community/

**Comment by ryukinix** [comment]
Vamos analisar o que é relevante então integrar ao frontpage. Sobre o YASWEG eu acho um tanto persistente o conselho. Sobre O slime instalando pelo código fonte é meio treta @commonlispbr/lispers

**Comment by ryukinix** [comment]
- [ ] Trocar YASWEG por https://github.com/kingcons/coleslaw (?)

**Comment by ryukinix** [comment]
Análise sobre uma possibilidade de usar LLVM no backend de SBCL para otimização do código nativo gerado: https://medium.com/@MartinCracauer/llvms-garbage-collection-facilities-and-sbcl-s-generational-gc-a13eedfb1b31

**Comment by luksamuk** [comment]
Isso é excelente! Abre também possibilidades para fazer interop com outras linguagens ou quem sabe até um port para WebAssembly (mas eu sei que estou sonhando alto, lol).

**Comment by ryukinix** [comment]
compilar os joguinhos SDL pra webassembly seria tão legal

**Comment by ryukinix** [comment]
Temos alguma coisa mesmo pra adicionar a mais? Acho que o front-end já tá bom.

**Comment by ryukinix** [comment]
Vou fechar isso aqui. Quem quiser completar o resto que abram depois e implemente o que falta.
