### ISSUE TITLE
Projeto Comunitário: Tradução do Cookbook de CL para Português

### ISSUE THREAD

**Issue by luksamuk** [commonlispbr/commonlispbr.github.io#11]
Como sugerido pelo post no Reddit parafraseado em #1, eu acho interessante discutir a viabilidade disso.
O [Cookbook de Common Lisp](https://lispcookbook.github.io/cl-cookbook/) é uma boa forma de começar a aprender mais sobre a linguagem, e talvez seja inclusive o que precisamos para ter mais pessoas entrando na comunidade.
Da mesma forma, pode ser uma contribuição internacional se, além de apenas traduzirmos, adicionarmos e completarmos o Cookbook com mais coisas que faltem.

**Comment by ryukinix** [comment]
Como gosto de ser afobado às vezes: o fork está [aqui](https://github.com/commonlispbr/cl-cookbook). Precisamos definir uma estratégia de tradução, assim como um ROADMAP tal como pessoas referentes a tradução, revisores e edição.

**Comment by luksamuk** [comment]
Isso seria um trabalho para o grupo no Telegram então, e talvez também consigamos gente no #lisp-br para nos ajudar.

**Comment by mateusfccp** [comment]
Considerando que já temos um repositório para isso e esse repositório é destinado ao site lisp.com.br, não faria sentido fechar essa _issue_?

**Comment by ryukinix** [comment]
Podemos fechar, sim. Acho que faz sentido. Essa issue precede o repositório
de tradução.

Cordialmente,
Manoel Vilela.

Em qua., 17 de abr. de 2024 10:37, Mateus Felipe C. C. Pinto <
***@***.***> escreveu:
