### ISSUE TITLE
Definir glossário

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#13]
Dado que é uma linguagem cheio de termos e jargões, seria muito interessante definir todos eles numa página única com o TOC gerado por heading das letras em ordem alfabética.

**Comment by luksamuk** [comment]
Isso poderia fazer parte do #15.

**Comment by ryukinix** [comment]
Faz sentido, inclusive vamos deixar isso como um arquivo separado. Quando reestruturarmos, iremos fazer isso como uma página dedicada.

**Comment by ryukinix** [comment]
@commonlispbr/lispers gostaria que nessa thread fosse discutida alguns termos incomuns para pessoas que não estão no mundo Lisp e que poderíamos adicionar no glossário para a fácil consulta e referência, tal como Lisp Machines, REPL, SLIME, Forms, Special-Forms, nil, Polish Notation, package, modules, systems (asdf), quicklisp e outras coisas que podem ser eventuamente úteis mas podem complicar iniciantes.

Definição de jargões em geral são bem vindos. Uma das principais paredes pra quem está entrando no mundo Lisp.

**Comment by luksamuk** [comment]
Então, vamos começar enumerando.
- [x] Lisp Machine
- [x] REPL
- [x] Slime
- [ ] Form, Special-Form
- [ ] nil
- [x] Polish Notation
- [x] Predicate
- [ ] Quoting
- [ ] Quasiquoting

Oriundas de outros lugares:
- [x] TL;DR
- [ ]  Arquivo da Tim (lol)


Ia ser legal irmos mantendo uma espécie de log dos termos, e aí a gente vai incorporando ao site.

**Comment by ryukinix** [comment]
Tá bom

**Comment by ryukinix** [comment]
Progresso em #40

**Comment by luksamuk** [comment]
O progresso está ótimo. Falta criar um link no site inicial para o Glossário.
