### ISSUE TITLE
Split reestruturação do frontend: gerar sitemap e desacoplar apêndice + projetos

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#15]
![image](https://user-images.githubusercontent.com/7642878/36092463-5cc37906-0fdf-11e8-8672-e3840a74d922.png)

Acredito que seja mais relevante criar páginas dedicadas para o apêndice e projetos, tal como temos agora uma seção dedicada pra regras.

Dessa maneira também iremos precisar escrever um sitemap. Acredito que seja interessante colocar o site primeiro como primeiro heading do org em index.org

**Comment by ryukinix** [comment]
Precisamos referenciar também aqui o repositório do https://github.com/commonlispbr/archive/ que poderemos colecionar alguns livros/livretos/apostilas que não estão facilmente na web.

**Comment by luksamuk** [comment]
Também acho válido o split.
Só acho que a coleção de livros tem que ser tratada com cuidado, não sei se podemos nos dar ao luxo de ferir copyright ~~abertamente~~.

**Comment by ryukinix** [comment]
Tudo bem. Vamos levar isso em consideração para os documentos dos quais tem copyright.

**Comment by ryukinix** [comment]
O site-map era interessante a gente gerar a partir de um +SRC_BLOCK do tipo elisp e meter no proprio org-mode então gerar o html dps :v é super magia mas fica bom

**Comment by ryukinix** [comment]
Mas qualquer coisa eu deixo o site-map automático pra outra thread. Vou fazer o basicão disso aqui logo

**Comment by AndersonTorres** [comment]
Os livros, bem, basta o link para a Amazon.
