### ISSUE TITLE
Definir makefile para compilação de todos os .org files

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#18]
ref: https://stackoverflow.com/questions/22072773/batch-export-of-org-mode-files-from-the-command-line

**Comment by luksamuk** [comment]
Será que existe alguma forma de fazer isso sem precisar do Emacs?
Não que exista algum outro editor de Org mais eficiente.

De qualquer forma, vou ver o que posso fazer pra essa issue.

**Comment by luksamuk** [comment]
Só uma dica para o futuro: Talvez seja bom  jogar os arquivos .html gerados em uma pasta docs/ e redirecionar o github-pages para lá.
Edit: Eu posso fazer isso, se quiser. Seria só o caso de adaptar o Makefile um pouco, mas a configuração para o Github redirecionar para a docs/ é com você.

**Comment by ryukinix** [comment]
Vamos mudar isso em breve, pois o makefile ainda não está ok. Está faltando funcionar o syntax highlight do arquivos exportados. Até isso funcionar provavelmente iremos precisar exportar manualmente com `C-c C-e h h`, o que cria automaticamente na pasta de edição, logo daria mais trabalho ter que ficar movendo direto, até inclusive sendo propenso a erros.

**Comment by ryukinix** [comment]
Achei algo que possa talvez ser útil: 
https://github.com/nhoffman/org-export

**Comment by ryukinix** [comment]
> Será que existe alguma forma de fazer isso sem precisar do Emacs?

Acho improvável. Mas por acaso se a gente achar poderia ser útil. Mas org... é mais fácil o cara ter o emacs se for precisar compilar isso aqui.

**Comment by ryukinix** [comment]
WOW! https://github.com/fniessen/orgmk
We should try this ^
