### ISSUE TITLE
Precisamos de um favicon de Common Lisp

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#21]
Talvez possamos gerar um através do lambda que usamos no frontpage da página 
![image](https://user-images.githubusercontent.com/7642878/36245847-fdf213a4-1224-11e8-9df7-60d546d13b5a.png)

O que acham @commonlispbr/lispers ?

**Comment by AndersonTorres** [comment]
Votação? Eu topo!

**Comment by ryukinix** [comment]
Obrigado @AndersonTorres. Que tal você gerar o favicon pra gente? : D

**Comment by ryukinix** [comment]
Estava vendo que o http://lisp-lang.org também já usa um lambda que aparece também no cookbook

**Comment by AndersonTorres** [comment]
Não sei gerar o icon :/

**Comment by ryukinix** [comment]
https://www.favicon-generator.org/

**Comment by AndersonTorres** [comment]
Que tal esse, em verde e amarelo para ficar bem chamativo?

https://imgur.com/a/rCPNi

**Comment by AndersonTorres** [comment]
Que tal esse, em verde e amarelo para ficar bem chamativo?
https://imgur.com/a/tAjTu

**Comment by ryukinix** [comment]
HMMMMMM!!! Estou tentado! Parece ser interessante, embora não goste tanto do contraste, de fato são as cores do nosso país e é o logo de CL.
