### ISSUE TITLE
Esclarecer o tópico sobre a criação de Common Lisp

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#23]
É conhecido que Common Lisp nasceu de uma especificação gerada por uma grande fusão de dialetos Lisp diversifcados da época dos anos '80. Nessa https://lisp.com.br/#sec-2-2 é descrito como Guy L. Steele o criador, o que pode ser um tanto muito forte, dado cunhos históricos que na verdade a ideia de criar a especificação nem foi dele.

Deveríamos referenciar isso e apenas atribuir ele como o autor da especificação, tal como referenciar os dialetos Lisp que tiveram influência para a criação de Common Lisp, tal como MacsLisp.

**Comment by ryukinix** [comment]
Acredito que o PR #26 poderia cuidar dessa tarefa também

**Comment by luksamuk** [comment]
Como disse em #26, acho que seria mais ideal criar um outro PR para isso, mas gosto da ideia.
Poderíamos fazer como uma espécie de árvore genealógica de CL.

**Comment by ryukinix** [comment]
Certo!

**Comment by hel-io** [comment]
Em 1970 Guy Steele e Gerald Sussman definiram um novo tipo de Lisp, chamado Scheme, que combinava algumas das ideias elegantes da família Algol de linguagem de programação com o poder da sintaxe e das estruturas de dados do Lisp.

No início dos anos 80, existiam dezenas de implementações Lisp incompatíveis, com cerca de meia dúzia de dialetos principais. Um projeto foi iniciado, liderado por Scott Fahlman, Daniel Weinreb, David Moon, Guy Steele e Richard Gabriel, para definir um Lisp comum que combinaria as melhores características dos dialetos existentes em um todo coerente.

A primeira edição do padrão Common Lisp apareceu em 1984; um padrão revisado apareceu em 1990. O padrão ANSI Common Lisp foi lançado em 1994 e revisado em 2004. Common Lisp tornou-se rapidamente o Lisp escolhido em ambientes acadêmicos e industriais. Os outros dialetos  praticamente desapareceram, com exceção do Scheme, que continua a desfrutar de uma popularidade modesta para aplicações educacionais.

Muitas das idéias mais importantes nos sistemas de programação surgiram em conexão com Lisp. Estas incluem a combinação de funções interpretadas e compiladas, coleta de lixo, chamadas de função recursiva, rastreamento e depuração no nível-fonte e editores direcionados de sintaxe. Atualmente,  Lisp é uma linguagem líder para pesquisa sofisticada sobre estilos de programação funcional, paralelo e orientada a objetos.

**Comment by hel-io** [comment]
fonte: Common Lisp - David S. Touretzky

**Comment by ryukinix** [comment]
@luksamuk  bora dar manutenção nesse repositório? Resolver as issues que abrimos em fevereiro. Essa aqui acho que dá pra concluir atualizando o documento no tópico "O que é Common Lisp?" com a descrição que o @hel-io ofereceu.
