### ISSUE TITLE
Corrigir link do avatar da página, usar fonte com SSL

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#4]
![image](https://user-images.githubusercontent.com/7642878/36068643-9c5f14da-0eb8-11e8-8804-f6384239ee8e.png)

A atual fonte usa HTTP na qual gera um problema de SSL por falta de segurança em ter arquivos sendo transferências sem proteção SSL.

![image](https://user-images.githubusercontent.com/7642878/36068645-afaba51c-0eb8-11e8-8cf2-08eba4a78b41.png)

**Comment by luksamuk** [comment]
Só comentando aqui para me lembrar de também RECRIAR A PÁGINA antes de mandar outro PR. Argh.

**Comment by ryukinix** [comment]
Se esqueceu? kkk

**Comment by luksamuk** [comment]
@ryukinix Sim, infelizmente. Só me lembrei depois do último PR.

**Comment by ryukinix** [comment]
Era bom fazer um git hook como pre-commit sabia? Gerar automaticamente o .html qndo vc mandasse git commit e adicionar tbm no stage. Vou depois tentar fazer.

**Comment by ryukinix** [comment]
https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks

**Comment by ryukinix** [comment]
Corrigido e regerado no último commit dado de: d03f1ed80ff2b5f57ab6ff06ba50d9f1941d22fe

**Comment by luksamuk** [comment]
@ryukinix Boa ideia. Farei.
