### ISSUE TITLE
Atraso na renderização (e não-renderização) do site

### ISSUE THREAD

**Issue by luksamuk** [commonlispbr/commonlispbr.github.io#41]
Andei notando recentemente que o site tem alguns problemas de renderização que não são imediatos, mas são inconveniências, sobretudo se assumirmos que novatos estão tentando acessar.

- Se o site nunca foi acessado, demora um pouco para que o texto apareça na tela.
- Se o site for acessado por um navegador que bloqueia certos tipos de script, o texto nunca aparece.

Por navegador que bloqueia certos tipos de script, leia-se: Firefox Klar, qualquer browser com a extensão uMatrix definida com _blacklisting_ de JavaScript por padrão, e potencialmente Tor Browser também.

Isso se torna bem irritante em conexões mais lentas, como mobile.

O problema parece estar intimamente relacionado ao setupfile utilizado. Pretendo inspecioná-lo melhor, e quem sabe fazer uma versão mais "lightweight" dele que possibilite renderização de texto independente de javascript.

**Comment by renanroberto** [comment]
Normalmente da pra resolver esse tipo de problema da font demorar a aparecer usando o `font-display: swap` no seu `@font-face`. Ficaria algo como

```
@font-face {
  font-family: 'sua-fonte';
  font-style: normal;
  font-display: swap;
}
```

Assim o site renderiza a fonte do sistema até a fonte escolhida carregar.

Mais informações em https://web.dev/font-display/

**Comment by luksamuk** [comment]
Depois de matutar um bocado com o Manoel, achei o culpado nos arquivos bundle.css dos temas longo e curto:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/4tJCtBv/photo-2020-10-31-21-06-20.jpg" alt="photo-2020-10-31-21-06-20" border="0"></a>

Basicamente, o HTML fica escondido por default, e os bundle.js reabilitam-no, mas só depois de carregar a webfont.

Sobre essa webfont, é um elemento de script externo, injetado dinamicamente pelo bundle.js na função `setupFonts`.

Logo mais subo um fix pra isso.

**Comment by ryukinix** [comment]
> Depois de matutar um bocado com o Manoel, achei o culpado nos arquivos bundle.css dos temas longo e curto:
> 
> [![photo-2020-10-31-21-06-20](https://camo.githubusercontent.com/5d9769036d6a3cf4ee51e15f3c760bf50b12b40d/68747470733a2f2f692e6962622e636f2f34744a437442762f70686f746f2d323032302d31302d33312d32312d30362d32302e6a7067)](https://imgbb.com/)
> 
> Basicamente, o HTML fica escondido por default, e os bundle.js reabilitam-no, mas só depois de carregar a webfont.
> 
> Sobre essa webfont, é um elemento de script externo, injetado dinamicamente pelo bundle.js na função `setupFonts`.
> 
> Logo mais subo um fix pra isso.

malandragem do cassete
