### ISSUE TITLE
Atualizar pagina lisp.com.br/projects.html

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#45]
- Indexar projetos dos membros do t.me/commonlispbr em CL
- Remover projetos não-brasileiros

Refatorar a apresentação numa tabela:

|project| description | author|
|---------| ----------------| -------|
| [lisp-chat] | Chat minimalista em terminal escrito em Common Lisp | [Manoel Vilela] | 
| [lisp-inference] | Motor de cálculo proposicional escrito em Common Lisp | [Manoel Vilela] |
| [leraxandria] | Coleção do utils em Common Lisp inspirado no alexandria | [Manoel Vilela] |
| [quicksys] | Gerenciador de múltiplas distribuições de QuickLisp | [Manoel Vilela], Lucas Vieira | 
| [trivial-snake] | Jogo da cobrinha escrito em Common Lisp e trivial-gamekit | [Manoel Vilela] |
| [cats] | Repositório de fotos de gatos com licença livre e geração de README.md escrito em Common Lisp | Mateus Felipe, [Manoel Vilela] |
| [spartns] | biblioteca para representação de matrizes e tensores em geral, esparsos. | Jerônimo Pellegrini |
| [brainfuck.lisp] | Interpretador de Brainfuck em Common Lisp num único arquivo | [Manoel Vilela] |
| [quickproject-cli.lisp] | Script bootstrapper para iniciar projetos na estrutura ASDF/Quicklisp | [Manoel Vilela] |
| [spartns](https://gitlab.com/jpellegrini/spartns) | biblioteca para representação de matrizes e tensores em geral, esparsos. | Jerônimo Pellegrini |

[quickproject-cli.lisp]: https://gist.github.com/ryukinix/b70e3d9bd99bfcad53976863c64d7b62
[brainfuck.lisp]: https://gist.github.com/ryukinix/fb616c042879660db5b43945267b28bf
[cats]: https://github.com/DestructHub/cats
[quicksys]: https://github.com/commonlispbr/quicksys
[leraxandria]: https://github.com/ryukinix/leraxandria
[trivial-snake]: https://github.com/ryukinix/trivial-snake
[lisp-chat]: https://github.com/ryukinix/lisp-chat
[lisp-inference]: https://github.com/ryukinix/lisp-inference
[spartns]: https://gitlab.com/jpellegrini/spartns
[Manoel Vilela]:  https://github.com/ryukinix

Quem tiver interesse, só adicionar uma linha como comentário baseado no layout da tabela acima. Veja exemplo em: https://github.com/commonlispbr/commonlispbr.github.io/issues/45#issuecomment-727629301.

EDIT: Irei atualizando a tabela de acordo com os colegas colaborando.

**Comment by jpellegrini** [comment]
>     * Remover projetos não-brasileiros

O que seria um projeto brasileiro -- qualquer um feito por brasileiro, mesmo que toda a documentação seja em Ingles?
Ou teria que ser tudo em pt_BR?

**Comment by mateusfccp** [comment]
O fato do Manoel incluir o projeto dele que é documentado em inglês me faz pensar que seja o primeiro caso.

**Comment by jpellegrini** [comment]
> O fato do Manoel incluir o projeto dele que é documentado em inglês me faz pensar que seja o primeiro caso.

Certo...

**Comment by renanroberto** [comment]
Gostei da ideia da tabela. A ideia é que os próprios membros poderão adicionar os seus projetos via PR?

> Remover projetos não-brasileiros

To de acordo. Talvez seja o caso de movê-los pra um "_awesome_" ou algo assim

**Comment by ryukinix** [comment]
> > O fato do Manoel incluir o projeto dele que é documentado em inglês me faz pensar que seja o primeiro caso.
> 
> Certo...

É relevante ter projetos com documentação inglês pois o feedback que recebi era de estrangeiros querendo saber o que tinha de contribuição no Brasil. Estar em português não vai ajudar muito. Mas esse não é o único público alvo, obviamente os brasileiros também e portanto alguns estarem em português é útil.

**Comment by ryukinix** [comment]
@renanroberto 
> Gostei da ideia da tabela. A ideia é que os próprios membros poderão adicionar os seus projetos via PR?

Sim.

**Comment by jpellegrini** [comment]
| project     | description                                         | author          |
|-------------|-----------------------------------------------------|-----------------|
| [spartns](https://gitlab.com/jpellegrini/spartns) | biblioteca para representação de matrizes e tensores em geral, esparsos. | Jerônimo Pellegrini |
