### ISSUE TITLE
Esse projeto ou grupo está ativo?

### ISSUE THREAD

**Issue by ghost** [commonlispbr/commonlispbr.github.io#46]
Olá a todos! Esse projeto ou grupo está ativo?

**Comment by parjanya** [comment]
bem, nosso grupo ainda existe e está ativo no telegram, mas não temos feito nada muito ambicioso ultimamente. pq?

**Comment by ghost** [comment]
Oi! Gostaria de participar, ultimamente estudo muito coisas como lisp. Onde está o link desse grupo do telegram de commonlisp?

**Comment by parjanya** [comment]
vc usa telegram? fale com a gente por lá :) https://t.me/commonlispbr

**Comment by ghost** [comment]
Oi! obrigado pelas informações, e fecha essa issue.
