### ISSUE TITLE
Estamos sem CI/CD: configurar github-action e remover travis

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#49]
O travis parou de funcionar há algum tempo para organizações com a conta gratuita.

A alternativa agora é usar o github-actions para poder fazer deploy do nosso site sem intervenção manual.

Lembrando que desenvolvimento na develop e a master é escrita com os arquivos em html gerado pelo org via `make`.

A ideia aqui é ter uma action do github que possa:

- executar sempre quando houver alteração na develop
- realizar `make` (depende docker)
- os resultados gerados salvar na branch master e fazer commit

**Comment by mateusfccp** [comment]
Para resolver isso, será que não converia eliminar a dependência do docker? Parece ser _overkill_ rodar um container dentro de um container :v

**Comment by ryukinix** [comment]
@mateusfccp poderia ser repensado pra ser sem, mas não acho que seja uma boa ideia. Com o docker temos as configurações já pré-estabelecidas de um emacs já configurado e pacotes baixados, pronto para o uso, fazer essa configuração via CI diretamente pode dar bastante trabalho atoa, e também não ser tão confiável, já que não há mecanismo de pinar versão do emacs do melpa por padrão, ele sempre baixa a mais atual. Dá pra tentar refatorar a configuração pra usar use-package, mas essa configuração aí que roda é a minha, não sei, eu não faria isso agora só por um ganho pequeno como esse.

Se alguém conseguir fazer funcionar bem, ok, remova o docker, mas do contrário não vejo justificativa plausível pra remoção. 

Além do mais, utilizar docker no CI/CD é comum. Se eles abstraem o runtime do CI (github actions, por ex) com docker ou não, problema deles. Com o travis funcionava bem, e atualmente tenho usado também docker em outros projetos sem problemas.

**Comment by ryukinix** [comment]
Solved with #65
