### ISSUE TITLE
Aumentar atributo css container max width para melhorar leitura

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#54]
# Como fazer

- [x] Aumentar para 1000px nos arquivos css:
  - [x] https://github.com/commonlispbr/commonlispbr.github.io/blob/master/org-theme/dist/short/bundle.css#L222
  - [x] https://github.com/commonlispbr/commonlispbr.github.io/blob/master/org-theme/dist/long/bundle.css#L222
- [x] Gerar PR para develop
- [x] Gerar PR para master com htmls + css atualizados

# Antes

![image](https://github.com/commonlispbr/commonlispbr.github.io/assets/7642878/5793a787-a0a0-4ac8-8db7-0b6080cd3f95)

# Depois

![image](https://github.com/commonlispbr/commonlispbr.github.io/assets/7642878/8eaf956e-e1c5-439f-91cf-7a325f617b01)

@commonlispbr/lispers

**Comment by mateusfccp** [comment]
Não tenho nenhuma opinião sobre essa mudança, mas posso fazer a mudança.
