### ISSUE TITLE
Sugestão: justificação + hifenização nos parágrafos

### ISSUE THREAD

**Issue by mateusfccp** [commonlispbr/commonlispbr.github.io#57]
Essa sugestão estava bloqueada pelo bug #55, mas agora que foi resolvido posso sugerir.

Atualmente, o corpo do texto de um parágrafo está com alinhação à esquerda:

<img width="749" alt="image" src="https://github.com/commonlispbr/commonlispbr.github.io/assets/4605213/2edd2349-82d5-4d80-a527-74ea25d19cf9">

Isso causa esses "serrilhados" no lado direito do texto, o que, opinião subjetiva, é feio.

Justificar o texto resolve o problema:

<img width="749" alt="image" src="https://github.com/commonlispbr/commonlispbr.github.io/assets/4605213/35b0d246-0a05-4bf5-a095-4f2b6126eb26">

O problema é que justificar o texto faz com que o espaçamento entre palavras seja variável (na imagem acima, se percebe bastante na segunda e penúltima linha), o que também pode resultar em um texto com espaçamento inconsistente e, opinião subjetiva, feio.

Minha proposta é habilitar justificação + hifenização:

<img width="749" alt="image" src="https://github.com/commonlispbr/commonlispbr.github.io/assets/4605213/14985a25-00a9-4067-ae89-799d5af2bef5">

Essa solução mantém o espaçamento entre palavras e deixa o texto alinhado, o que é, opinião subjetiva, esteticamente melhor.

**Comment by mateusfccp** [comment]
Caso seja de entendimento comum que essa é uma melhoria na tipografia do site, posso abrir um PR com a solução.

**Comment by ryukinix** [comment]
Fique a vontade! Aceitamos contribuição e ela é bem-vinda @mateusfccp 

Acredito que essa melhoria topográfica do texto ficaria melhor de ler.
