### ISSUE TITLE
Aumentar variável css --container-max-width de 700px para 1000px ou maior

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/commonlispbr.github.io#61]
# Premissa

Acredito que atualmente o site tem uma largura muito baixa, com baixo aproveitamento de leitura. 

# Atualmente: 700px

![image](https://github.com/commonlispbr/commonlispbr.github.io/assets/7642878/7616f372-8c97-48d6-b49b-c4d49baf4f88)

# Sugerido: 1000px

![image](https://github.com/commonlispbr/commonlispbr.github.io/assets/7642878/b4779548-1a7c-455b-9ec7-eab0b0350c41)

# O que mudar

Setar variável  `--container-max-width` para 1000px em:

- https://github.com/commonlispbr/commonlispbr.github.io/blob/develop/org-theme/dist/long/bundle.css#L222
- https://github.com/commonlispbr/commonlispbr.github.io/blob/develop/org-theme/dist/short/bundle.css#L222

Fazer deploy novamente das páginas, como feito em #60 ¹

¹ rodar `make all` para gerar arquivos htmls e atualizar arquivos da branch `master`

@luksamuk @parjanya @mateusfccp

**Comment by mateusfccp** [comment]
Isso não é um duplicado do #54?

**Comment by ryukinix** [comment]
Pior que é uma duplicada descarada. E pra piorar foi eu que criei a outra
também. A velhice tá chegando. Vamos fechar essa.

Cordialmente,
Manoel Vilela.

Em ter., 16 de abr. de 2024 22:40, Mateus Felipe C. C. Pinto <
***@***.***> escreveu:
