### ISSUE TITLE
Não estamos mais servindo arquivos minificados

### ISSUE THREAD

**Issue by mateusfccp** [commonlispbr/commonlispbr.github.io#63]
Por algum motivo, no _commit_ 9f5858fab436054e8c33839cd1e2fc17276cd72b os arquivos minificados foram apagados e os arquivos `.setup` estão configurados para servir os arquivos não minificados.

Como o _commit_ foi feito sem passar por processo de revisão, imagino que pode ter sido um engano (a pessoa pode ter desabilitado a minificação para debugar mais facilmente localmente e esqueceu de reverter). Não vejo motivo para servir os arquivos não minificados.

Proponho reverter essa parte do _commit_ e voltar a servir os arquivos minificados, o que deve melhorar o tempo de carregamento da página, mesmo que marginalmente.

**Comment by ryukinix** [comment]
Acredito que tenha sido minha culpa quando fui editar e achei mais conveniente deixar sem ser minificado. O ideal é deixar minificado apenas na master e o processo de deployment fazer a minificação automaticamente, senão ficaria propenso a acontecer esse mesmo deslize na próxima edição dos arquivos de css na branch develop.

**Comment by mateusfccp** [comment]
Antigamente, a minificação acontecia em que momento? Não encontrei no repositório nenhum script que faça isso.

**Comment by mateusfccp** [comment]
> O ideal é deixar minificado apenas na master e o processo de deployment fazer a minificação automaticamente, senão ficaria propenso a acontecer esse mesmo deslize na próxima edição dos arquivos de css na branch develop.

Normalmente se usa _source maps_, justamente para resolver esse problema. Se minifica tudo, mas na hora de depurar os _source maps_ vão restaurar o arquivo "original".

**Comment by ryukinix** [comment]
Por mim tudo bem usar source maps também, comentei com esse fluxo porque é
pra próximo do que já temos hoje. Qualquer proposta que resolva isso e que
seja melhor que atual, ok. Preferia honestamente que o problema do deploy
automatizado fosse resolvido antes disso.

Em qua., 17 de abr. de 2024 às 15:43, Mateus Felipe C. C. Pinto <
***@***.***> escreveu:

**Comment by mateusfccp** [comment]
> Antigamente, a minificação acontecia em que momento? Não encontrei no repositório nenhum script que faça isso.

Favor responder essa pergunta.

---

Sobre o deploy automatizado, acho que está relacionado e pode ser resolvido junto, já que a minificação faz parte do CI.

**Comment by ryukinix** [comment]
Não acontecia, por isso foi removido. Era manual.

Cordialmente,
Manoel Vilela.

Em qua., 17 de abr. de 2024 17:01, Mateus Felipe C. C. Pinto <
***@***.***> escreveu:

**Comment by mateusfccp** [comment]
Imagino que eu não tenha me expressado bem. Ainda que o arquivo fosse minificado manualmente, alguma ferramenta era usada para fazê-lo. Eu imagino que o "manual" queira dizer que era feito na máquina local e depois copiado para o source; não creio que queira dizer que você, literalmente, minificava manualmente, removendo espaço por espaço e trocando nomes perfeitamente semânticos por nomes obscuros no seu editor de texto.

A pergunta é, unicamente, para entender se há a preferência de uso de alguma ferramenta específica no processo de minificação. Eu poderia usar qualquer coisa, mas estou respeitando o que já estava sendo feito anteriormente em vez de tentar impor minhas preferências.

**Comment by ryukinix** [comment]
Ok! Entendi agora. Perdão pela confusão.

Eu costumava usar essa: https://github.com/tdewolff/minify

É boa o suficiente e fácil de instalar no CI.

Pode usar esse comando:

```
go install github.com/tdewolff/minify/cmd/minify@latest
```

Pra aplicar:

```
minify main.css
```

Ele suporte minificação de vários outros arquivos também.
